gems:
- asciidoctor
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
markdown: kramdown
asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay
    - coderay-css=style